"""add posting frequency config

Revision ID: 6877f550575a
Revises: 3ff414956f6e
Create Date: 2026-09-02 11:47:39.304640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6877f550575a'
down_revision: Union[str, Sequence[str], None] = '3ff414956f6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketing_preferences', sa.Column('posting_frequency_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketing_preferences', 'posting_frequency_config')
    # ### end Alembic commands ###
