"""add storage documents

Revision ID: dc96d5d3fdc7
Revises: b0638ba5406f
Create Date: 2026-09-08 02:13:30.303956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc96d5d3fdc7'
down_revision: Union[str, Sequence[str], None] = 'b0638ba5406f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_documents',
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('storage_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storage_documents')
    # ### end Alembic commands ###
